meta:
  extract_upstream: false

executor:
  dotted_path: ploomber.executors.Parallel
  processes: 4 # limit to a max of 2 processes
  start_method: spawn # start child process using 'spawn' method

tasks:
  - source: site_replacement.site_replacement_global_parameters_
    product: cache/site_replacement_global_parameters_.pkl
    name: site_replacement_global_parameters_

  - source: site_replacement.read_all_reefs_data_
    product: cache/read_all_reefs_data_.pkl
    upstream: [site_replacement_global_parameters_]

  - source: site_replacement.read_all_reefs_data_show_
    product: cache/read_all_reefs_data_show_.pkl
    upstream: [read_all_reefs_data_]

  - source: site_replacement.read_all_temporal_summary_
    product: cache/read_all_temporal_summary_.pkl
    upstream: [read_all_reefs_data_]

  - source: site_replacement.read_all_temporal_summary_plot_
    product: cache/read_all_temporal_summary_plot_.png
    upstream: [read_all_temporal_summary_, site_replacement_global_parameters_]

    ## All sampled reefs --------------------------------------------------
  - source: site_replacement.read_sampled_reefs_data_
    product: cache/read_sampled_reefs_data_.pkl
    upstream: [site_replacement_global_parameters_]

  - source: site_replacement.read_sampled_reefs_data_show_
    product: cache/read_sampled_reefs_data_show_.pkl
    upstream: [read_sampled_reefs_data_]

  - source: site_replacement.sampled_simple_raw_means_ 
    product: cache/sampled_simple_raw_means_.pkl
    upstream: [read_sampled_reefs_data_]

  - source: site_replacement.sampled_simple_raw_means_plot_
    product: cache/sampled_simple_raw_means_plot_.png
    upstream: [site_replacement_global_parameters_, sampled_simple_raw_means_]

    ## Replace a reef --------------------------------------------------
  - source: site_replacement.read_sampled_reefs_data_1_
    product: cache/read_sampled_reefs_data_1_
    upstream: [site_replacement_global_parameters_]

  - source: site_replacement.read_sampled_reefs_data_1_show_
    product: cache/read_sampled_reefs_data_1_show_.pkl
    upstream: [read_sampled_reefs_data_1_]

  - source: site_replacement.sampled_reefs_data_1_plot_
    product: cache/sampled_reefs_data_1_plot_.png
    upstream: [site_replacement_global_parameters_, read_sampled_reefs_data_1_]

    ## Replace a reef (V2) ---------------------------------------------
  - source: site_replacement.read_sampled_reefs_data_2_
    product: cache/read_sampled_reefs_data_2_
    upstream: [site_replacement_global_parameters_]

  - source: site_replacement.read_sampled_reefs_data_2_show_
    product: cache/read_sampled_reefs_data_2_show_.pkl
    upstream: [read_sampled_reefs_data_2_]

  - source: site_replacement.sampled_reefs_data_2_plot_
    product: cache/sampled_reefs_data_2_plot_.png
    upstream: [site_replacement_global_parameters_, read_sampled_reefs_data_2_]

    ## Data transformations
    ## All sampled reefs ------------------------------------------------
  - source: site_replacement.sampled_reefs_data_prep_0_
    product: cache/sampled_reefs_data_prep_0_.pkl
    upstream: [site_replacement_global_parameters_, read_sampled_reefs_data_]

  - source: site_replacement.newdata_0_
    product: cache/newdata_0_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_data_prep_0_]

    ## Replace a reef --------------------------------------------------
  - source: site_replacement.sampled_reefs_data_prep_1_
    product: cache/sampled_reefs_data_prep_1_.pkl
    upstream: [site_replacement_global_parameters_, read_sampled_reefs_data_1_]

  - source: site_replacement.newdata_1_
    product: cache/newdata_1_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_data_prep_1_]

    ## Replace a reef (V2) ---------------------------------------------
  - source: site_replacement.sampled_reefs_data_prep_2_
    product: cache/sampled_reefs_data_prep_2_.pkl
    upstream: [site_replacement_global_parameters_, read_sampled_reefs_data_2_]

  - source: site_replacement.newdata_2_
    product: cache/newdata_2_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_data_prep_2_]

    ## Modelled trends
    ## All sampled reefs ------------------------------------------------
  - source: site_replacement.sampled_reefs_bart_data_0_
    product: cache/sampled_reefs_bart_data_0_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_data_prep_0_]

  - source: site_replacement.sampled_reefs_bart_fit_0_
    product: cache/sampled_reefs_bart_fit_0_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_data_0_]

  - source: site_replacement.sampled_reefs_bart_prep_plot_0_
    product: cache/sampled_reefs_bart_prep_plot_0_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_fit_0_, sampled_reefs_bart_data_0_]

  - source: site_replacement.sampled_reefs_bart_plot_0_
    product: cache/sampled_reefs_bart_plot_0_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_prep_plot_0_]

  - source: site_replacement.sampled_reefs_bart_prep_plot_0c_
    product: cache/sampled_reefs_bart_prep_plot_0c_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_fit_0_, sampled_reefs_bart_data_0_]

  - source: site_replacement.sampled_reefs_bart_plot_0c_
    product: cache/sampled_reefs_bart_plot_0c_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_prep_plot_0c_]

    ## Replace a reef --------------------------------------------------
  - source: site_replacement.sampled_reefs_bart_data_1_
    product: cache/sampled_reefs_bart_data_1_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_data_prep_1_]

  - source: site_replacement.sampled_reefs_bart_fit_1_
    product: cache/sampled_reefs_bart_fit_1_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_data_1_]

  - source: site_replacement.sampled_reefs_bart_prep_plot_1_
    product: cache/sampled_reefs_bart_prep_plot_1_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_fit_1_, sampled_reefs_bart_data_1_]

  - source: site_replacement.sampled_reefs_bart_plot_1_
    product: cache/sampled_reefs_bart_plot_1_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_prep_plot_1_]

  - source: site_replacement.sampled_reefs_bart_prep_plot_1c_
    product: cache/sampled_reefs_bart_prep_plot_1c_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_fit_1_, sampled_reefs_bart_data_1_]

  - source: site_replacement.sampled_reefs_bart_plot_1c_
    product: cache/sampled_reefs_bart_plot_1c_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_prep_plot_1c_]

    ## Replace a reef (V2) ---------------------------------------------

  - source: site_replacement.sampled_reefs_bart_data_2_
    product: cache/sampled_reefs_bart_data_2_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_data_prep_2_]

  - source: site_replacement.sampled_reefs_bart_fit_2_
    product: cache/sampled_reefs_bart_fit_2_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_data_2_]

  - source: site_replacement.sampled_reefs_bart_prep_plot_2_
    product: cache/sampled_reefs_bart_prep_plot_2_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_fit_2_, sampled_reefs_bart_data_2_]

  - source: site_replacement.sampled_reefs_bart_plot_2_
    product: cache/sampled_reefs_bart_plot_2_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_prep_plot_2_]

  - source: site_replacement.sampled_reefs_bart_prep_plot_2c_
    product: cache/sampled_reefs_bart_prep_plot_2c_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_fit_2_, sampled_reefs_bart_data_2_]

  - source: site_replacement.sampled_reefs_bart_plot_2c_
    product: cache/sampled_reefs_bart_plot_2c_.pkl
    upstream: [site_replacement_global_parameters_, sampled_reefs_bart_prep_plot_2c_]

  ## - source: site_replacement.sampled_reefs_bart_prep_0_
  ##   product: cache/sampled_reefs_bart_prep_0_.pkl
  ##   upstream: [site_replacement_global_parameters_, sampled_reefs_data_prep_0_]

  ## - source: site_replacement.sampled_reefs_bart_fit_0_
  ##   product: cache/sampled_reefs_bart_fit_0_.pkl
  ##   upstream: [site_replacement_global_parameters_, sampled_reefs_bart_prep_0_]

  ## - source: site_replacement.sampled_reefs_bart_post_0_
  ##   product: cache/sampled_reefs_bart_post_0_.pkl
  ##   upstream: [site_replacement_global_parameters_, sampled_reefs_bart_fit_0_, sampled_reefs_bart_prep_0_]

  ## - source: site_replacement.sampled_reefs_bart_plot_0_
  ##   product: cache/sampled_reefs_bart_plot_0_.pkl
  ##   upstream: [site_replacement_global_parameters_, sampled_reefs_bart_post_0_, sampled_reefs_bart_prep_0_]

  ## - source: site_replacement.sampled_reefs_bart_post_0c_
  ##   product: cache/sampled_reefs_bart_post_0c_.pkl
  ##   upstream: [site_replacement_global_parameters_, sampled_reefs_bart_prep_0_, sampled_reefs_bart_fit_0_]

  ## - source: site_replacement.sampled_reefs_bart_plot_0c_
  ##   product: cache/sampled_reefs_bart_plot_0c_.pkl
  ##   upstream: [site_replacement_global_parameters_, sampled_reefs_bart_post_0c_, sampled_reefs_bart_prep_0_]

  ## - source: site_replacement.test
  ##   product: cache/test.pkl
  ##   upstream: [site_replacement_global_parameters_, sampled_reefs_bart_fit_0_, sampled_reefs_bart_data_0_]

  ## Missing years =========================================================================
  - source: missing_years.missing_years_global_parameters_
    product: cache/missing_years_global_parameters_.pkl
    name: missing_years_global_parameters_

  - source: missing_years.missing_years_read_all_reefs_data_
    product: cache/missing_years_read_all_reefs_data_.pkl
    upstream: [missing_years_global_parameters_]

  - source: missing_years.missing_years_read_all_reefs_data_show_
    product: cache/missing_years_read_all_reefs_data_show_.pkl
    upstream: [missing_years_read_all_reefs_data_]

  - source: missing_years.missing_years_read_all_temporal_summary_
    product: cache/missing_years_read_all_temporal_summary_.pkl
    upstream: [missing_years_read_all_reefs_data_]

  - source: missing_years.missing_years_read_all_temporal_summary_plot_
    product: cache/missing_years_read_all_temporal_summary_plot_.png
    upstream: [missing_years_read_all_temporal_summary_, missing_years_global_parameters_]

    ## All sampled reefs --------------------------------------------------
  - source: missing_years.missing_years_read_sampled_reefs_data_
    product: cache/missing_years_read_sampled_reefs_data_.pkl
    upstream: [missing_years_global_parameters_]

  - source: missing_years.missing_years_read_sampled_reefs_data_show_
    product: cache/missing_years_read_sampled_reefs_data_show_.pkl
    upstream: [missing_years_read_sampled_reefs_data_]

  - source: missing_years.missing_years_sampled_simple_raw_means_ 
    product: cache/missing_years_sampled_simple_raw_means_.pkl
    upstream: [missing_years_read_sampled_reefs_data_]

  - source: missing_years.missing_years_sampled_simple_raw_means_plot_
    product: cache/missing_years_sampled_simple_raw_means_plot_.png
    upstream: [missing_years_global_parameters_, missing_years_sampled_simple_raw_means_]

    ## Temporal gap some reefs -------------------------------------------
  - source: missing_years.read_sampled_reefs_data_3_
    product: cache/read_sampled_reefs_data_3_
    upstream: [missing_years_global_parameters_]

  - source: missing_years.read_sampled_reefs_data_3_show_
    product: cache/read_sampled_reefs_data_3_show_.pkl
    upstream: [read_sampled_reefs_data_3_]

  - source: missing_years.sampled_reefs_data_3_plot_
    product: cache/sampled_reefs_data_3_plot_.png
    upstream: [missing_years_global_parameters_, read_sampled_reefs_data_3_]

    ## Temporal gap all reefs -------------------------------------------
  - source: missing_years.read_sampled_reefs_data_4_
    product: cache/read_sampled_reefs_data_4_
    upstream: [missing_years_global_parameters_]

  - source: missing_years.read_sampled_reefs_data_4_show_
    product: cache/read_sampled_reefs_data_4_show_.pkl
    upstream: [read_sampled_reefs_data_4_]

  - source: missing_years.sampled_reefs_data_4_plot_
    product: cache/sampled_reefs_data_4_plot_.png
    upstream: [missing_years_global_parameters_, read_sampled_reefs_data_4_]

    ## Data transformations
    ## All sampled reefs ------------------------------------------------
  - source: missing_years.missing_years_sampled_reefs_data_prep_0_
    product: cache/missing_years_sampled_reefs_data_prep_0_.pkl
    upstream: [missing_years_global_parameters_, missing_years_read_sampled_reefs_data_]

  - source: missing_years.missing_years_newdata_0_
    product: cache/missing_years_newdata_0_.pkl
    upstream: [missing_years_global_parameters_, missing_years_sampled_reefs_data_prep_0_]

    ## Temporal gap some reefs -------------------------------------------

  - source: missing_years.sampled_reefs_data_prep_3_
    product: cache/sampled_reefs_data_prep_3_.pkl
    upstream: [missing_years_global_parameters_, read_sampled_reefs_data_3_]

  - source: missing_years.newdata_3_
    product: cache/newdata_3_.pkl
    upstream: [missing_years_global_parameters_, sampled_reefs_data_prep_3_]

    ## Temporal gap all reefs -------------------------------------------

  - source: missing_years.sampled_reefs_data_prep_4_
    product: cache/sampled_reefs_data_prep_4_.pkl
    upstream: [missing_years_global_parameters_, read_sampled_reefs_data_4_]

  - source: missing_years.newdata_4_
    product: cache/newdata_4_.pkl
    upstream: [missing_years_global_parameters_, sampled_reefs_data_prep_4_]


    ## Modelled trends
    ## All sampled reefs ------------------------------------------------
  - source: missing_years.missing_years_sampled_reefs_bart_data_0_
    product: cache/missing_years_sampled_reefs_bart_data_0_.pkl
    upstream: [missing_years_global_parameters_, missing_years_sampled_reefs_data_prep_0_]

  - source: missing_years.missing_years_sampled_reefs_bart_fit_0_
    product: cache/missing_years_sampled_reefs_bart_fit_0_.pkl
    upstream: [missing_years_global_parameters_, missing_years_sampled_reefs_bart_data_0_]

  - source: missing_years.missing_years_sampled_reefs_bart_prep_plot_0_
    product: cache/missing_years_sampled_reefs_bart_prep_plot_0_.pkl
    upstream: [missing_years_global_parameters_, missing_years_sampled_reefs_bart_fit_0_, missing_years_sampled_reefs_bart_data_0_]

  - source: missing_years.missing_years_sampled_reefs_bart_plot_0_
    product: cache/missing_years_sampled_reefs_bart_plot_0_.pkl
    upstream: [missing_years_global_parameters_, missing_years_sampled_reefs_bart_prep_plot_0_]

  - source: missing_years.missing_years_sampled_reefs_bart_prep_plot_0c_
    product: cache/missing_years_sampled_reefs_bart_prep_plot_0c_.pkl
    upstream: [missing_years_global_parameters_, missing_years_sampled_reefs_bart_fit_0_, missing_years_sampled_reefs_bart_data_0_]

  - source: missing_years.missing_years_sampled_reefs_bart_plot_0c_
    product: cache/missing_years_sampled_reefs_bart_plot_0c_.pkl
    upstream: [missing_years_global_parameters_, missing_years_sampled_reefs_bart_prep_plot_0c_]

    ## Temporal gap some reefs -------------------------------------------

  - source: missing_years.sampled_reefs_bart_data_3_
    product: cache/sampled_reefs_bart_data_3_.pkl
    upstream: [missing_years_global_parameters_, sampled_reefs_data_prep_3_]

  - source: missing_years.sampled_reefs_bart_fit_3_
    product: cache/sampled_reefs_bart_fit_3_.pkl
    upstream: [missing_years_global_parameters_, sampled_reefs_bart_data_3_]

  - source: missing_years.sampled_reefs_bart_prep_plot_3_
    product: cache/sampled_reefs_bart_prep_plot_3_.pkl
    upstream: [missing_years_global_parameters_, sampled_reefs_bart_fit_3_, sampled_reefs_bart_data_3_]

  - source: missing_years.sampled_reefs_bart_plot_3_
    product: cache/sampled_reefs_bart_plot_3_.pkl
    upstream: [missing_years_global_parameters_, sampled_reefs_bart_prep_plot_3_]

  - source: missing_years.sampled_reefs_bart_prep_plot_3c_
    product: cache/sampled_reefs_bart_prep_plot_3c_.pkl
    upstream: [missing_years_global_parameters_, sampled_reefs_bart_fit_3_, sampled_reefs_bart_data_3_]

  - source: missing_years.sampled_reefs_bart_plot_3c_
    product: cache/sampled_reefs_bart_plot_3c_.pkl
    upstream: [missing_years_global_parameters_, sampled_reefs_bart_prep_plot_3c_]

    ## Temporal gap all reefs -------------------------------------------

  - source: missing_years.sampled_reefs_bart_data_4_
    product: cache/sampled_reefs_bart_data_4_.pkl
    upstream: [missing_years_global_parameters_, sampled_reefs_data_prep_4_]

  - source: missing_years.sampled_reefs_bart_fit_4_
    product: cache/sampled_reefs_bart_fit_4_.pkl
    upstream: [missing_years_global_parameters_, sampled_reefs_bart_data_4_]

  - source: missing_years.sampled_reefs_bart_prep_plot_4_
    product: cache/sampled_reefs_bart_prep_plot_4_.pkl
    upstream: [missing_years_global_parameters_, sampled_reefs_bart_fit_4_, sampled_reefs_bart_data_4_]

  - source: missing_years.sampled_reefs_bart_plot_4_
    product: cache/sampled_reefs_bart_plot_4_.pkl
    upstream: [missing_years_global_parameters_, sampled_reefs_bart_prep_plot_4_]

  - source: missing_years.sampled_reefs_bart_prep_plot_4c_
    product: cache/sampled_reefs_bart_prep_plot_4c_.pkl
    upstream: [missing_years_global_parameters_, sampled_reefs_bart_fit_4_, sampled_reefs_bart_data_4_]

  - source: missing_years.sampled_reefs_bart_plot_4c_
    product: cache/sampled_reefs_bart_plot_4c_.pkl
    upstream: [missing_years_global_parameters_, sampled_reefs_bart_prep_plot_4c_]
