name: Build and render analyses

on:
  workflow_dispatch:
#  pull_request:
#  push:
#    branches: ['release']

jobs:
  build-analyses:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    name: ${{ matrix.config.r }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - { r: '4.4.1' }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0  # ensure that more than the last commit is checked out so that we can get time stamps
      # Restore the timestamps - I am going to try to use these to work out what is new and what is not    
      - name: Restore Timestamps
        uses: chetan/git-restore-mtime-action@v1

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev make

      # install R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.R }}

      - name: Repos
        run: |
          cat("\noptions(repos=c(stan='https://mc-stan.org/r-packages/',CRAN ='https://cloud.r-project.org'))\n", file = "~/.Rprofile", append = TRUE)
        shell: Rscript {0}
        
      ## Install R packages
      - name: install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::rmarkdown
            any::quarto
            any::tidyverse
            any::sf
            any::DHARMa
            any::glmmTMB
            any::patchwork
            any::brms
            any::knitr
            any::simstudy